# -*- coding: utf-8 -*-
"""Telecom_Disaster_prediction(EDA).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wlydwG53CaAAAY-_15aJmTFMkoDlrrTu
"""

!pip install sdv pandas numpy matplotlib seaborn scikit-learn -q

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

df = pd.read_csv('/content/p1.csv', on_bad_lines='skip')

start_date = pd.to_datetime('2025-06-01 00:00:00')

df['timestamp'] = pd.date_range(
    start=start_date,
    periods=len(df),
    freq='h'
)


print(df['timestamp'].head(10))


print(df['timestamp'].dt.strftime('%Y-%m-%d %H:%M:%S').head(10))

np.random.seed(42)


crisis = (
    (df['temperature'] > 45) &
    (df['power_load'] > 85) &
    (df['smoke_level'] > 18) &
    (df['equipment_age_years'] > 12)
)

df.loc[crisis, 'failure'] = 1


print("(failure = 1) ", df['failure'].sum())
print( round(df['failure'].mean() * 100, 2), "%")


df.to_csv('p2.csv', index=False)

print(df.shape)
print(df.head())

df= pd.read_csv('/content/p2.csv')

print(df.columns.tolist())

iiot = pd.read_csv('/content/simulated_iiot_dataset.csv')
pm = pd.read_csv('/content/ai4i2020.csv')

iiot_selected = iiot[['temperature', 'vibration', 'pressure', 'humidity', 'rotation_speed',
                      'voltage', 'current', 'motor_temperature', 'machine_failure']].copy()

pm_selected = pm[['Air temperature [K]', 'Process temperature [K]', 'Rotational speed [rpm]',
                  'Torque [Nm]', 'Tool wear [min]', 'Machine failure']].copy()

df = df.copy()

df['vibration'] = iiot['vibration'].sample(len(df), replace=True).values
df['motor_temp'] = iiot['motor_temperature'].sample(len(df), replace=True).values
df['voltage'] = iiot['voltage'].sample(len(df), replace=True).values

print("الأعمدة النهائية:", df.columns.tolist())
print(df.head())

print(df.columns.tolist())

df.shape

duplicates_before =df.duplicated().sum()
print(duplicates_before )

import matplotlib.pyplot as plt

plt.figure(figsize=(15,6))

df.boxplot()

plt.xticks(rotation=90)

plt.title("Boxplot for All Features")

plt.show()

def detect_outliers_iqr(data):
    Q1 = data.quantile(0.25)
    Q3 = data.quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return ((data < lower_bound) | (data > upper_bound))

outliers_count = {}
for col in df.select_dtypes(include=np.number).columns:
    outliers = detect_outliers_iqr(df[col])
    outliers_count[col] = outliers.sum()

print(" Outliers ")
for col, count in sorted(outliers_count.items(), key=lambda x: x[1], reverse=True):
    print(f"{col}: {count} outlier")

missing =df.isnull().sum()
print(missing)

import numpy as np

def handle_outliers(df, columns):
    for col in columns:
        if col not in df.columns:
            print(f"Warning: Column '{col}' not found in DataFrame. Skipping outlier handling for this column.")
            continue
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR
        df[col] = df[col].clip(lower=lower, upper=upper)
    return df

# الأعمدة اللي عندها outliers
outlier_cols = ['failure', 'smoke_level', 'temp_mean', 'wind_speed', 'voltage_fluctuation',
                'network_traffic', 'power_load', 'humidity_mean', 'voltage', 'vibration',
                'temperature', 'motor_temp']

df = handle_outliers(df, outlier_cols)

print("تم معالجة الـ Outliers")
print("عدد الصفوف:", len(df))

def detect_outliers_iqr(data):
    Q1 = data.quantile(0.25)
    Q3 = data.quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return ((data < lower_bound) | (data > upper_bound))

outliers_count = {}
for col in df.select_dtypes(include=np.number).columns:
    outliers = detect_outliers_iqr(df[col])
    outliers_count[col] = outliers.sum()

print(" Outliers ")
for col, count in sorted(outliers_count.items(), key=lambda x: x[1], reverse=True):
    print(f"{col}: {count} outlier")

from sklearn.preprocessing import RobustScaler
import joblib

SENSOR_COLUMNS = [
    "temperature", "humidity", "power_load", "network_traffic", "smoke_level",
    "equipment_age_years", "voltage_fluctuation", "precipitation", "wind_speed",
    "vibration", "motor_temp", "voltage",
]

PHYSICAL_BOUNDS = {
    "temperature": (-10, 150),
    "humidity": (0, 100),
    "power_load": (0, 200),
    "network_traffic": (0, 5000),
    "smoke_level": (0, 500),
    "vibration": (0, 20),
    "motor_temp": (0, 200),
    "voltage": (150, 280),
    "voltage_fluctuation": (0, 100),
}

def load_data(path: str) -> pd.DataFrame:
    df = pd.read_csv(path, parse_dates=["timestamp"])
    df = df.sort_values("timestamp").reset_index(drop=True)
    return df


def clip_physical_bounds(df: pd.DataFrame) -> pd.DataFrame:
    for col, (low, high) in PHYSICAL_BOUNDS.items():
        if col in df.columns:
            df[col] = df[col].clip(lower=low, upper=high)
    return df

def handle_missing_values(df: pd.DataFrame) -> pd.DataFrame:
    df = df.set_index("timestamp")
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    # Interpolation زمني - أنسب لبيانات الحساسات المتسلسلة
    df[numeric_cols] = df[numeric_cols].interpolate(method="time").bfill().ffill()
    df = df.reset_index()
    return df

def remove_outliers_iqr(df: pd.DataFrame, cols=None, factor: float = 3.0) -> pd.DataFrame:
    """يستبدل القيم الشاذة المتطرفة (وليس حذفها حتى لا نفقد صفوف حرجة قرب الحوادث)."""
    cols = cols or SENSOR_COLUMNS
    for col in cols:
        if col not in df.columns:
            continue
        q1, q3 = df[col].quantile([0.25, 0.75])
        iqr = q3 - q1
        lower, upper = q1 - factor * iqr, q3 + factor * iqr
        df[col] = df[col].clip(lower=lower, upper=upper)
    return df

def scale_features(df: pd.DataFrame, cols=None, scaler_path="models/scaler.pkl", fit=True):
    cols = cols or SENSOR_COLUMNS
    cols = [c for c in cols if c in df.columns]
    if fit:
        scaler = RobustScaler()
        df[cols] = scaler.fit_transform(df[cols])
        joblib.dump(scaler, scaler_path)
    else:
        scaler = joblib.load(scaler_path)
        df[cols] = scaler.transform(df[cols])
    return df, cols

def preprocess_pipeline(raw_path: str, save_path: str = "data/processed_data.csv") -> pd.DataFrame:
    df = load_data(raw_path)
    df = clip_physical_bounds(df)
    df = handle_missing_values(df)
    df = remove_outliers_iqr(df)
    df.to_csv(save_path, index=False)
    print(f"✅ Preprocessing تم بنجاح | الشكل النهائي: {df.shape} -> {save_path}")
    return df

df.shape

def detect_outliers_iqr(data):
    Q1 = data.quantile(0.25)
    Q3 = data.quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return ((data < lower_bound) | (data > upper_bound))

outliers_count = {}
for col in df.select_dtypes(include=np.number).columns:
    outliers = detect_outliers_iqr(df[col])
    outliers_count[col] = outliers.sum()

print(" Outliers ")
for col, count in sorted(outliers_count.items(), key=lambda x: x[1], reverse=True):
    print(f"{col}: {count} outlier")

missing =df.isnull().sum()
print(missing)

"""
preprocessing.py
----------------------------------
تنظيف ومعالجة بيانات الحساسات:
- تحويل التاريخ/الوقت
- معالجة القيم المفقودة (Interpolation)
- معالجة القيم الشاذة (IQR / physical bounds)
- إعادة ترتيب زمني وفرز
- Scaling (يُحفظ الـ Scaler لإعادة استخدامه في الإنتاج)
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import RobustScaler
import joblib

SENSOR_COLUMNS = [
    "temperature", "humidity", "power_load", "network_traffic", "smoke_level",
    "equipment_age_years", "voltage_fluctuation", "precipitation", "wind_speed",
    "vibration", "motor_temp", "voltage",
]

# حدود فيزيائية منطقية لكل حساس (لإزالة القراءات المستحيلة/الخاطئة من الجهاز)
PHYSICAL_BOUNDS = {
    "temperature": (-10, 150),
    "humidity": (0, 100),
    "power_load": (0, 200),
    "network_traffic": (0, 5000),
    "smoke_level": (0, 500),
    "vibration": (0, 20),
    "motor_temp": (0, 200),
    "voltage": (150, 280),
    "voltage_fluctuation": (0, 100),
}


def load_data(path: str) -> pd.DataFrame:
    df = pd.read_csv(path, parse_dates=["timestamp"])
    df = df.sort_values("timestamp").reset_index(drop=True)
    return df


def clip_physical_bounds(df: pd.DataFrame) -> pd.DataFrame:
    for col, (low, high) in PHYSICAL_BOUNDS.items():
        if col in df.columns:
            df[col] = df[col].clip(lower=low, upper=high)
    return df


def analyze_missing_values(df: pd.DataFrame, drop_threshold: float = 0.4) -> tuple[list, pd.DataFrame]:
    """
    يحلل نسبة الفقد لكل عمود ويحدد:
    - أعمدة "فقد بسيط" (< drop_threshold) -> تُعالج بالـ Interpolation
    - أعمدة "فقد كارثي" (>= drop_threshold) -> تُحذف لأن تعبئتها تضيف Noise وليس إشارة حقيقية
      (غالبًا سبب هذا النوع: عمود جاء من مصدر خارجي مثل Weather API ولم يتطابق مع أغلب الصفوف)
    """
    missing_pct = (df.isna().sum() / len(df)).sort_values(ascending=False)
    report = missing_pct.to_frame("missing_pct")
    report["missing_count"] = df.isna().sum()
    report["decision"] = np.where(
        report["missing_pct"] >= drop_threshold, "DROP (فقد كارثي)",
        np.where(report["missing_pct"] > 0, "INTERPOLATE (فقد بسيط)", "OK")
    )
    cols_to_drop = report[report["missing_pct"] >= drop_threshold].index.tolist()
    print("📋 تقرير القيم المفقودة:")
    print(report[report["missing_count"] > 0])
    if cols_to_drop:
        print(f"\n⚠️ سيتم حذف هذه الأعمدة (فقد >= {drop_threshold:.0%}): {cols_to_drop}")
    return cols_to_drop, report


def handle_missing_values(df: pd.DataFrame, drop_threshold: float = 0.4) -> pd.DataFrame:
    cols_to_drop, _ = analyze_missing_values(df, drop_threshold)
    df = df.drop(columns=cols_to_drop)

    # date عمود مشتق من timestamp أصلاً -> نعيد اشتقاقه بدل تعبئته (يقفل أي فجوة فيه 100%)
    if "date" in df.columns:
        df["date"] = df["timestamp"].dt.date

    df = df.set_index("timestamp")
    numeric_cols = df.select_dtypes(include=[np.number]).columns
    non_numeric_cols = df.columns.difference(numeric_cols)

    # Interpolation زمني للأعمدة الرقمية - أنسب لبيانات الحساسات المتسلسلة
    df[numeric_cols] = df[numeric_cols].interpolate(method="time").bfill().ffill()
    # ffill/bfill لأي عمود نصي/تصنيفي متبقي (احتياطي)
    if len(non_numeric_cols) > 0:
        df[non_numeric_cols] = df[non_numeric_cols].ffill().bfill()

    df = df.reset_index()

    # failure عمود تصنيفي (0/1) - نضمن رجوعه Integer بعد أي Interpolation
    if "failure" in df.columns:
        df["failure"] = df["failure"].round().astype(int)

    return df


def remove_outliers_iqr(df: pd.DataFrame, cols=None, factor: float = 3.0) -> pd.DataFrame:
    """يستبدل القيم الشاذة المتطرفة (وليس حذفها حتى لا نفقد صفوف حرجة قرب الحوادث)."""
    cols = cols or SENSOR_COLUMNS
    for col in cols:
        if col not in df.columns:
            continue
        q1, q3 = df[col].quantile([0.25, 0.75])
        iqr = q3 - q1
        lower, upper = q1 - factor * iqr, q3 + factor * iqr
        df[col] = df[col].clip(lower=lower, upper=upper)
    return df

def scale_features(df: pd.DataFrame, cols=None, scaler_path="models/scaler.pkl", fit=True):
    cols = cols or SENSOR_COLUMNS
    cols = [c for c in cols if c in df.columns]
    if fit:
        scaler = RobustScaler()
        df[cols] = scaler.fit_transform(df[cols])
        joblib.dump(scaler, scaler_path)
    else:
        scaler = joblib.load(scaler_path)
        df[cols] = scaler.transform(df[cols])
    return df, cols


def preprocess_pipeline(raw_path: str, save_path: str = "data/processed_data.csv") -> pd.DataFrame:
    df = load_data(raw_path)
    df = clip_physical_bounds(df)
    df = handle_missing_values(df)
    df = remove_outliers_iqr(df)
    df.to_csv(save_path, index=False)
    print(f"✅ Preprocessing تم بنجاح | الشكل النهائي: {df.shape} -> {save_path}")
    return df

missing =df.isnull().sum()
print(missing)

def detect_outliers_iqr(data):
    Q1 = data.quantile(0.25)
    Q3 = data.quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return ((data < lower_bound) | (data > upper_bound))

outliers_count = {}
for col in df.select_dtypes(include=np.number).columns:
    outliers = detect_outliers_iqr(df[col])
    outliers_count[col] = outliers.sum()

print(" Outliers ")
for col, count in sorted(outliers_count.items(), key=lambda x: x[1], reverse=True):
    print(f"{col}: {count} outlier")

q1, q3 = df["humidity"].quantile([0.25, 0.75])
iqr = q3 - q1
lower, upper = q1 - 3 * iqr, q3 + 3 * iqr

n_outliers = ((df["humidity"] < lower) | (df["humidity"] > upper)).sum()
print(f"⚠️ عدد الـ outliers في humidity قبل المعالجة: {n_outliers}")

df["humidity"] = df["humidity"].clip(lower=lower, upper=upper)
print(f"✅ تم Clip القيم الشاذة بين {lower:.2f} و {upper:.2f}")

import pandas as pd

df = pd.read_csv("/content/p2.csv", parse_dates=["timestamp"])

# هل القيم الموجودة (غير الناقصة) بتتكرر باليوم؟ لو أيوه يبقى فعلاً بيانات يومية اتعمل لها merge
sample_day = df.dropna(subset=["temp_mean"])["date"].iloc[0]
print(df[df["date"] == sample_day][["date", "temp_mean"]].head(10))

# كام يوم فريد أصلاً موجود ليهم قيمة طقس؟
print("عدد الأيام اللي فيها بيانات طقس:", df.dropna(subset=["temp_mean"])["date"].nunique())
print("عدد الأيام الكلي في الداتا:", df["date"].nunique())

df["timestamp"] = pd.to_datetime(df["timestamp"])
df["date"] = pd.to_datetime(df["date"])
df["month"] = df["date"].dt.month

known = df.dropna(subset=["temp_mean"])[["date", "month", "temp_mean"]].drop_duplicates("date")
print(known.groupby("month")["temp_mean"].agg(["count", "mean"]))

weather_cols = ["temp_mean", "humidity_mean", "precipitation", "wind_speed"]

for col in weather_cols:
    monthly_avg = df.groupby("month")[col].transform("mean")  # بيتحسب من الـ 50 يوم المعروفين بس
    df[col] = df[col].fillna(monthly_avg)
    df[col] = df[col].fillna(df[col].mean())  # أي شهر مالوش عينة خالص

df = df.drop(columns=["month"])
print("متبقي فقد:", df[weather_cols].isna().sum().sum())

import pandas as pd

df["timestamp"] = pd.to_datetime(df["timestamp"])
df["date"] = pd.to_datetime(df["date"])
df["month"] = df["date"].dt.month

# 1) متوسطات مناخية معيارية للقاهرة (Climate Normals) - تُستخدم fallback بس
CAIRO_CLIMATE_NORMALS = {
    #        temp_mean  humidity_mean  precipitation  wind_speed(km/h)
    1:  {"temp_mean": 14.0, "humidity_mean": 59, "precipitation": 5,  "wind_speed": 14},
    2:  {"temp_mean": 15.7, "humidity_mean": 57, "precipitation": 6,  "wind_speed": 15},
    3:  {"temp_mean": 18.4, "humidity_mean": 55, "precipitation": 4,  "wind_speed": 16},
    4:  {"temp_mean": 21.8, "humidity_mean": 52, "precipitation": 2,  "wind_speed": 17},
    5:  {"temp_mean": 25.5, "humidity_mean": 46, "precipitation": 1,  "wind_speed": 16},
    6:  {"temp_mean": 27.6, "humidity_mean": 45, "precipitation": 0,  "wind_speed": 15},
    7:  {"temp_mean": 28.8, "humidity_mean": 58, "precipitation": 0,  "wind_speed": 14},
    8:  {"temp_mean": 28.5, "humidity_mean": 61, "precipitation": 0,  "wind_speed": 13},
    9:  {"temp_mean": 26.8, "humidity_mean": 60, "precipitation": 0,  "wind_speed": 13},
    10: {"temp_mean": 24.0, "humidity_mean": 59, "precipitation": 1,  "wind_speed": 13},
    11: {"temp_mean": 19.5, "humidity_mean": 60, "precipitation": 3,  "wind_speed": 13},
    12: {"temp_mean": 15.8, "humidity_mean": 57, "precipitation": 6,  "wind_speed": 13},
}

weather_cols = ["temp_mean", "humidity_mean", "precipitation", "wind_speed"]

for col in weather_cols:
    # الأولوية: متوسط الشهر من عينتك الحقيقية (لو موجودة)
    monthly_avg_real = df.groupby("month")[col].transform("mean")
    df[col] = df[col].fillna(monthly_avg_real)

    # لو الشهر مالوش ولا يوم واحد في عينتك -> استخدم القيمة المناخية المعيارية لنفس الشهر
    still_missing = df[col].isna()
    df.loc[still_missing, col] = df.loc[still_missing, "month"].map(
        lambda m: CAIRO_CLIMATE_NORMALS[m][col]
    )

df = df.drop(columns=["month"])
print("متبقي فقد بعد الحل:", df[weather_cols].isna().sum().sum())

missing =df.isnull().sum()
print(missing)

def detect_outliers_iqr(data):
    Q1 = data.quantile(0.25)
    Q3 = data.quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return ((data < lower_bound) | (data > upper_bound))

outliers_count = {}
for col in df.select_dtypes(include=np.number).columns:
    outliers = detect_outliers_iqr(df[col])
    outliers_count[col] = outliers.sum()

print(" Outliers ")
for col, count in sorted(outliers_count.items(), key=lambda x: x[1], reverse=True):
    print(f"{col}: {count} outlier")

df.shape

# أعمدة الحساسات الفعلية اللي منطقي نطبق عليها IQR (قراءات معدات، ممكن يحصل فيها خطأ قياس)
OUTLIER_COLUMNS = [
    "temperature", "humidity", "power_load", "network_traffic",
    "smoke_level", "voltage_fluctuation", "vibration", "motor_temp", "voltage",
]
# ملاحظة: استبعدنا عمدًا:
# - failure          -> Label/Target مش قراءة حساس، وتطبيق IQR عليه بيدمر إشارة العطل الحقيقية
# - temp_mean/humidity_mean/wind_speed/precipitation -> بيانات طقس موسمية، الفروق بينها طبيعية مش شذوذ
# - equipment_age_years -> صفة ثابتة نسبيًا للمعدة، مش قراءة لحظية

def remove_outliers_iqr(df, cols=OUTLIER_COLUMNS, factor=3.0):
    for col in cols:
        if col not in df.columns:
            continue
        q1, q3 = df[col].quantile([0.25, 0.75])
        iqr = q3 - q1
        lower, upper = q1 - factor * iqr, q3 + factor * iqr
        n_outliers = ((df[col] < lower) | (df[col] > upper)).sum()
        print(f"{col}: {n_outliers} outlier -> Clip بين {lower:.2f} و {upper:.2f}")
        df[col] = df[col].clip(lower=lower, upper=upper)
    return df

df = remove_outliers_iqr(df)

df.to_csv('p3.csv', index=False)

