# -*- coding: utf-8 -*-
"""Telecom_Disaster_prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cSu8gX66cqf2lpa7mPG1lz0iDesny1j9

**Data Creation**
"""

pip install sdv pandas numpy

!pip install sdv pandas numpy matplotlib seaborn scikit-learn xgboost

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

"""Real Patterns"""

import pandas as pd
import numpy as np


np.random.seed(42)

n_rows = 20000

data = pd.DataFrame({
    'timestamp': pd.date_range(start='2025-01-01', periods=n_rows, freq='H'),
    'temperature': np.random.normal(32, 12, n_rows),  # درجة حرارة
    'humidity': np.random.normal(55, 18, n_rows),      # رطوبة
    'power_load': np.random.normal(75, 18, n_rows),      # حمل الكهرباء (%)
    'network_traffic': np.random.normal(68, 22, n_rows),    # حركة الشبكة
    'smoke_level': np.random.normal(8, 5, n_rows),         # مستوى الدخان
    'equipment_age_years': np.random.randint(1, 25, n_rows),
    'voltage_fluctuation': np.random.normal(5, 3, n_rows),
})

"""# Simulate crisis like Ramses Fire (ظروف خطرة)"""

crisis_condition = (
    (data['temperature'] > 48) &
    (data['power_load'] > 92) &
    (data['smoke_level'] > 20)
)

data['failure'] = 0
data.loc[crisis_condition, 'failure'] = 1

!pip install sdv -q

from sdv.single_table import CTGANSynthesizer
from sdv.metadata import SingleTableMetadata

metadata = SingleTableMetadata()
metadata.detect_from_dataframe(data)

print("Metadata created successfully!")

synthesizer = CTGANSynthesizer(
    metadata,
    epochs=200,
    batch_size=500,
    verbose=True
)

print("|SDV...")
synthesizer.fit(data)

synthetic_data = synthesizer.sample(num_rows=50000)

print("Synthetic Data!")
print("Shape", synthetic_data.shape)
print(synthetic_data.head())

import requests
import pandas as pd

# جلب Weather Data حوالين تاريخ الحريق (يوليو 2025)
def get_weather_around_fire():
    url = "https://archive-api.open-meteo.com/v1/archive"
    params = {
        "latitude": 30.0444,   # القاهرة - رمسيس
        "longitude": 31.2357,
        "start_date": "2025-06-01",   # شهر قبل الحريق
        "end_date": "2025-07-20",     # بعد الحريق بقليل
        "daily": ["temperature_2m_mean", "relative_humidity_2m_mean", "precipitation_sum", "wind_speed_10m_max"],
        "timezone": "Africa/Cairo"
    }

    response = requests.get(url, params=params)

    if response.status_code == 200:
        weather = response.json()
        df_weather = pd.DataFrame({
            'date': pd.to_datetime(weather['daily']['time']),
            'temp_mean': weather['daily']['temperature_2m_mean'],
            'humidity_mean': weather['daily']['relative_humidity_2m_mean'],
            'precipitation': weather['daily']['precipitation_sum'],
            'wind_speed': weather['daily']['wind_speed_10m_max']
        })
        print("تم جلب Weather Data بنجاح حوالين 7/7/2025!")
        print(df_weather.head(10))
        print(f"\nعدد الأيام: {len(df_weather)}")
        return df_weather
    else:
        print("Error:", response.status_code)
        print(response.text)
        return None

weather_df = get_weather_around_fire()

# توحيد التواريخ - هنخلي كل الداتا في 2025
# أولاً: تعديل الـ synthetic data

synthetic_data['timestamp'] = pd.date_range(
    start='2025-06-01',
    periods=len(synthetic_data),
    freq='H'
)

print("تم تعديل تواريخ Synthetic Data لتبدأ من يونيو 2025")
print(synthetic_data['timestamp'].min(), "إلى", synthetic_data['timestamp'].max())

# حفظ النسخة المعدلة
synthetic_data.to_csv('synthetic_telecom_disaster_final.csv', index=False)
print("تم حفظ الملف النهائي")

# دمج الـ Weather Data مع Synthetic Data

# أولاً: تحويل Weather Data لتكون hourly (لأن synthetic data hourly)
weather_df['date'] = pd.to_datetime(weather_df['date'])
weather_df = weather_df.set_index('date').resample('H').ffill().reset_index()

# Merge on date (approximate match)
synthetic_data['date'] = synthetic_data['timestamp'].dt.date
weather_df['date'] = weather_df['date'].dt.date

merged_data = pd.merge(
    synthetic_data,
    weather_df,
    on='date',
    how='left'
)

print("تم الدمج بنجاح!")
print("شكل الداتا النهائية:", merged_data.shape)
print("\nأعمدة الداتا النهائية:")
print(merged_data.columns.tolist())

# حفظ الداتا النهائية
merged_data.to_csv('p1.csv', index=False)
print("\nتم حفظ الملف النهائي: p1.csv")

"""Explore Data"""

print("Data format", data.shape)

print("\n(failure = 1):", data['failure'].sum())

print(data.head())

print( data.shape)

